#######################################################################################################################
# Upsun demo project configuration
#######################################################################################################################
# Application configuration.
applications:    
    # App 1: Frontend (JS)
    frontend:

        source:
            root: "frontend"

        type: "nodejs:18"

        build:
            flavor: none

        variables:
            env:
                REACT_APP_BACKEND_URL: "/"
                npm_config_loglevel: silent
                NPM_CONFIG_UPDATE_NOTIFIER: false

        hooks:
            build: |
                set -eux
                npm install
                export REACT_APP_PROJECT_ID=$PLATFORM_PROJECT
                npm run build
            deploy: |
                bash scripts/api.sh

        web:
            locations:
                /:
                    root: build
                    index:
                        - index.html
                    expires: 2m
                    scripts: false
                    allow: true
                    rules:
                        static\/*:
                            expires: 365d
                /api/v1/environment:
                    root: api
                    index:
                        - index.json
                    allow: true
                    scripts: false
        mounts:
            api:
                source: storage
                source_path: api



    
# Routes configuration.
routes:
    "https://{default}/":
        id: frontend
        type: upstream
        primary: true
        upstream: "frontend:http"

    "https://www.{default}":
        id: frontend-redirect
        type: redirect
        to: "https://{default}/"